### ISSUE TITLE
Error: Can't login with gmail. 

### ISSUE THREAD

**Issue by isabeen** [Ajoor-App/ajoor-project#112]
![dd](https://user-images.githubusercontent.com/53593496/64162509-e66f2b80-ce58-11e9-89b5-101699b3e815.JPG)

**Comment by danialshakeel** [comment]
Working fine with the localhost, sending you a video on teams. The person with access to google developers account need to add the http://www.aajoor.com for google API calls.

**Comment by isabeen** [comment]
Waiting for settings change, for verification.
