### ISSUE TITLE
Sign Up: Stuck at Number Verification. (Code isn't receiving)

### ISSUE THREAD

**Issue by isabeen** [Ajoor-App/ajoor-project#116]
It asks to tick the 'I am not a robot checkbox' and click send code.
After clicking the 'send code' button the checkbox again appears asking to be filled, instead of saying 'code is sending e.t.c' and code is also not received.

**Comment by isabeen** [comment]
**Following changes required in the sign up screen:**
-Ask country code in sign up screen
-Make phone number editable on the phone number verification screen

**Comment by isabeen** [comment]
Same issue. Doesn't send code in any condition. Same errors occurring. @danialshakeel

**Comment by isabeen** [comment]
@danialshakeel can you share the id which you creating using the web .

I am never able to receive code. Please let know if you were successful.
We can then test this together.

**Comment by danialshakeel** [comment]
@isabeen the functionality works for the localhost, i have explained before that maybe the webapp domain is not added in the firebase console.

**Comment by danialshakeel** [comment]
feel free to test these on localhost until it is added to the firebase console by maryam.

**Comment by isabeen** [comment]
@danialshakeel  will check it once @maryam-awan adds it to the firebase console
