### ISSUE TITLE
Forgot Password: Stuck at 'Send code' button. (can't change password)

### ISSUE THREAD

**Issue by isabeen** [Ajoor-App/ajoor-project#117]
![xxx](https://user-images.githubusercontent.com/53593496/64168284-9eee9c80-ce64-11e9-8e31-1f5afbaf1acd.JPG)

**Comment by danialshakeel** [comment]
@isabeen you moved this back to in progress without any comment.

**Comment by isabeen** [comment]
@danialshakeel Not working

**Comment by isabeen** [comment]
@danialshakeel  never sends the code

**Comment by isabeen** [comment]
will check it once @maryam-awan adds it to the firebase console
