### ISSUE TITLE
Logo of aajoor needs to be changed

### ISSUE THREAD

**Issue by maryam-awan** [Ajoor-App/ajoor-project#165]
![b4xgkvqyfmmpj4ab0fma aajjor](https://user-images.githubusercontent.com/40426826/65749987-c44b8f00-e120-11e9-90b9-435ddf3e5898.png)

**Comment by isabeen** [comment]
@mohsinabid Logo's background should be white instead of transparent, I guess. @maryam-awan please confirm this.

Also, only the 1st letter of Aajoor should be capital.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/53593496/66291398-25cae500-e8fb-11e9-814d-03f7191f131d.png)
