### ISSUE TITLE
Change the font color on cover page when Azeez asks.

### ISSUE THREAD

**Issue by maryam-awan** [Ajoor-App/ajoor-project#168]
![iStock-488892637-2](https://user-images.githubusercontent.com/40426826/65751434-075b3180-e124-11e9-87ad-357d88c1f0f0.jpg)

**Comment by danialshakeel** [comment]
What kind of change is this ? Explanation ?

**Comment by danialshakeel** [comment]
I remember everyone agreed on this that we are not providing any text editing options for.

**Comment by isabeen** [comment]
will verify when @maryam-awan gives a go-ahead.
