### ISSUE TITLE
Change name: ajoor to 'aajoor' in notification messages & invitation email

### ISSUE THREAD

**Issue by isabeen** [Ajoor-App/ajoor-project#173]
![WhatsApp Image 2019-10-07 at 11 16 03 AM](https://user-images.githubusercontent.com/53593496/66288807-1eeca400-e8f4-11e9-9a1f-3d195f5f80ad.jpeg)

**Comment by sheerazanwar** [comment]
Will you please elaborate?
Where you specifically found this issue from backend which needs to be resolved?

**Comment by sheerazanwar** [comment]
Is there anyone who will respond to my query?
@maryam-awan @isabeen

**Comment by isabeen** [comment]
@sheerazanwar  Notification messages

**Comment by sheerazanwar** [comment]
Mentioning and giving example both are different things. Kindly be more precise as i have to do many thing on multiple projects at the same time.

**Comment by isabeen** [comment]
@sheerazanwar checked by making a new scheme. 
![nn](https://user-images.githubusercontent.com/53593496/67194488-a405ac00-f410-11e9-9de3-6b0d18a26b97.jpeg)

**Comment by isabeen** [comment]
@sheerazanwar we need to implement the changes in aajoor invitation email too.
![WhatsApp Image 2019-10-21 at 2 35 34 PM (1)](https://user-images.githubusercontent.com/53593496/67194551-c5ff2e80-f410-11e9-8abf-1edbfbb5582f.jpeg)
