### ISSUE TITLE
App Icon needs to be changed for notification bar

### ISSUE THREAD

**Issue by isabeen** [Ajoor-App/ajoor-project#193]
Also make the title **Aajoor.**

![WhatsApp Image 2019-10-08 at 11 54 24 AM](https://user-images.githubusercontent.com/53593496/66373802-eb2c7f80-e9c2-11e9-8ce3-9f378fae1c80.jpeg)

**Comment by mohsinabid** [comment]
Done

**Comment by isabeen** [comment]
@mohsinabid  let me know when the title is changed too.

**Comment by mohsinabid** [comment]
Done
