### ISSUE TITLE
Profile picture preview: Issue only in menu bar preview not the account settings (see screenshot) 

### ISSUE THREAD

**Issue by isabeen** [Ajoor-App/ajoor-project#82]
The picture was set as profile picture in iOS. Then it was logged in on an android phone which shows a more zoomed version of it.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/53593496/63757741-0db37f00-c8d4-11e9-9e12-0c39a61a61f5.png)

**Comment by mohsinabid** [comment]
@isabeen ios main kesy show ho raha ha. I think its fine

**Comment by isabeen** [comment]
> @isabeen ios main kesy show ho raha ha. I think its fine

@mohsinabid 

![a9d8a045-8690-420f-8ce0-d34bb0152fb0](https://user-images.githubusercontent.com/53593496/63918513-43807100-ca56-11e9-992a-8bd6d1f4158d.jpg)


![e03d7061-1bfb-4899-b64c-f30c80e696e0](https://user-images.githubusercontent.com/53593496/63918529-49765200-ca56-11e9-8d09-12d9714d7df4.jpg)

**Comment by isabeen** [comment]
Dev Comments: "Thats not a big issue, but right now it can create problems and I have to focus on other issues so I will solve those issue which are error or spelling mistakes"

QA Comments: To be dealt later.
